# Generated by Django 2.1.2 on 2021-06-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestSummary",
            fields=[],
            options={
                "verbose_name": "Request Summary",
                "verbose_name_plural": "Requests Summary",
                "proxy": True,
                "indexes": [],
            },
            bases=("course.request",),
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ("abbr",),
                "verbose_name": "Activity Type",
                "verbose_name_plural": "Activity Types",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ("-year", "course_code")},
        ),
        migrations.AlterModelOptions(
            name="request",
            options={"ordering": ["-status", "-created"]},
        ),
        migrations.AddField(
            model_name="course",
            name="crosslisted_request",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tied_course",
                to="course.Request",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="primary_crosslist",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="request",
            name="admin_additional_instructions",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="process_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="school",
            name="form_additional_enrollments",
            field=models.BooleanField(
                default=True, verbose_name="Additional Enrollments Form Field"
            ),
        ),
        migrations.AlterField(
            model_name="autoadd",
            name="role",
            field=models.CharField(
                choices=[
                    ("TA", "TA"),
                    ("INST", "Instructor"),
                    ("DES", "Designer"),
                    ("LIB", "Librarian"),
                    ("OBS", "Observer"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="canvassite",
            name="request_instance",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course.Request",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="multisection_request",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="additional_sections",
                to="course.Request",
            ),
        ),
    ]
