# Generated by Django 2.1.2 on 2021-06-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_auto_20210621_1344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
